### ISSUE TITLE
Gridless Functionality

### ISSUE THREAD

**Issue by VexxMyst** [manuelVo/foundryvtt-terrain-ruler#11]
So I just started messing with Enhanced Terrain Layer and love it; but I've run into a rather significant problem (for me).

While a square grid works perfectly fine and counts difficult terrain properly...
![Screenshot (397)](https://user-images.githubusercontent.com/74265604/117208516-37b88680-adc3-11eb-92b0-e88d6a93df58.png)

...A gridless map does not.
![Screenshot (398)](https://user-images.githubusercontent.com/74265604/117208644-5fa7ea00-adc3-11eb-9178-6b0381e56edb.png)

As can be evidenced by the Measure Distance with Difficult Terrain tab likewise disappearing between images, I believe this is an issue with this module.

**Comment by manuelVo** [comment]
Gridless is currenlty unsupported, because pulling that off is quite some work, but it's on my roadmap :)

**Comment by VexxMyst** [comment]
I figured that was the case, glad to hear it's being worked on!

**Comment by VexxMyst** [comment]
I can't tell you how excited I am to see that this has been implemented. Thank you.
