### ISSUE TITLE
Large errors with Starfinder system, Foundry 8.7

### ISSUE THREAD

**Issue by Ironxxx** [manuelVo/foundryvtt-terrain-ruler#15]
Hi. I'm using Drag Ruler (speed attribute is actor.data.data.attributes.speed.value for Starfinder) and Enhanced Terrain Layer and both are working fine in 8.7. However, adding Terrain Ruler to the mix I get a lot of errors when just moving a token and difficult terrain is not being counted, though the option is turned on:
```js
api.js:114 TypeError: Cannot read property 'contains' of null
    at TerrainLayer.cost (terrainlayer.js:161)
    at Object.getCostEnhancedTerrainlayer [as getCost] (measure.js:25)
    at speed_provider.js:70
    at Array.map (<anonymous>)
    at GenericSpeedProvider.getCostForStep (speed_provider.js:70)
    at getCostFromSpeedProvider (api.js:111)
    at opts.costFunction (compatibility.js:31)
    at measure.js:81
    at Array.map (<anonymous>)
    at measureDistancesSquare (measure.js:32)
getCostFromSpeedProvider @ api.js:114
opts.costFunction @ compatibility.js:31
(anonymous) @ measure.js:81
measureDistancesSquare @ measure.js:32
measureDistances @ measure.js:17
measureDistances @ compatibility.js:34
measure @ foundry_imports.js:200
measure @ ruler.js:60
scheduleMeasurement @ foundry_imports.js:134
(anonymous) @ foundry_imports.js:145
setTimeout (async)
scheduleMeasurement @ foundry_imports.js:145
onMouseMove @ foundry_imports.js:126
onEntityLeftDragMove @ main.js:150
entityType._onDragLeftMove @ main.js:68
callback @ foundry.js:35473
_handleDragMove @ foundry.js:35803
_handleMouseMove @ foundry.js:35777
a.emit @ index.js:202
r.dispatchEvent @ interaction.min.js:8
r.processPointerMove @ interaction.min.js:8
t.recursiveFindHit @ interaction.min.js:8
t.findHit @ interaction.min.js:8
r.processInteractive @ interaction.min.js:8
r.onPointerMove @ interaction.min.js:8
terrain-main.js:11 Enhanced Terrain Layer |  ruler DragRulerRuler {_events: i, _eventsCount: 0, tempDisplayObjectParent: null, transform: t, alpha: 1, …}
```

**Comment by manuelVo** [comment]
What version of Enhacned Terrain Layer are you using?

**Comment by Ironxxx** [comment]
1.0.31 which I think is the latest
Terrain Layer 1.3.1
Drag Ruler 1.7.5

**Comment by Ironxxx** [comment]
I've tried an empty world with just those three modules and there is no error and the modules work fine.
However, I have tried my main Starfinder world with just those modules and get the errors 
Absolutely no idea...

**Comment by manuelVo** [comment]
In this case, if you can share the world in which the bug happens, that would immensely help fixing the issue.

**Comment by Ironxxx** [comment]
On further investigation it appears to be issues with older player character tokens, including ones I only created a few days ago. Newer tokens are fine. Not sure what the change was. Would you stil like the world.json?

**Comment by manuelVo** [comment]
Does it happen on new maps with grid size 50?

**Comment by Ironxxx** [comment]
No. I setup a new map with the exact same settings and it was fine. I duplicated the original map and the copy still has errors

**Comment by Ironxxx** [comment]
I've worked it out. I had a lot of difficult terrain squares. Deleting them and reapplying them fixed it.

**Comment by manuelVo** [comment]
Good to hear! In that case it was likely an issue in Enhanced Terrain Layer. Closing this, as it's fixed now and doesn't seem likely to happen again.
