### ISSUE TITLE
Dont work this  Enhanced Terrain Layer

### ISSUE THREAD

**Issue by CaosFR** [manuelVo/foundryvtt-terrain-ruler#19]
Hi,

Thanks for you mod :)
I have a problem with your mod. I use Enhanced Terrain Layer with your mod (and Drag ruler for the mouvement).
When I move a token to a diffucult terrain nothing happens.

The ruler stop to work if "Measure Distance with Diffucult Terrain" is check "On" from the toolbox. I dont use Diffucult Terrain so maybe it's normal.
<img width="448" alt="Capture" src="https://user-images.githubusercontent.com/37581932/140548488-8330e9df-5b20-467a-9051-2dd6a547b287.PNG">

Thanks

**Comment by manuelVo** [comment]
Press F12 to open the JS console and see if any errors (red) or warnings (yellow) show up. If so, please post a screenshot of them here.

**Comment by CaosFR** [comment]
Thanks again, yes I have a big red error. You can see it in attached file :
[foundry.rp.fr-1636132410209.log](https://github.com/manuelVo/foundryvtt-terrain-ruler/files/7487783/foundry.rp.fr-1636132410209.log)
r

**Comment by manuelVo** [comment]
This is a bug that's happening in Enhanced Terrain Layer currently. There's some invalid invisible terrain (with no width and no height) in your scene. Unfortunately the only way I know to work around this issue is to delete terrain until the bug is gone and then rebuild from there.

**Comment by CaosFR** [comment]
I have delete all terrain and it's work now. Unfortunately the bug come back some time.
I will wait a new version :)
