### ISSUE TITLE
Compatibility with Drag Ruler

### ISSUE THREAD

**Issue by Iankid** [manuelVo/foundryvtt-terrain-ruler#2]
seems there's some compatibility issues with the mod Drag Ruler. making Drag Ruler act oddly,
I would also like to ask if you can not only fix the compatibility issue, but allow this mod to work off of Drag Ruler as well.

**Comment by manuelVo** [comment]
Please specify what "act oddly" exactly means. As for having Drag Ruler work with Terrain Measurements that's a job that needs to be done in Drag Ruler and is tracked in https://github.com/manuelVo/foundryvtt-drag-ruler/issues/1

**Comment by manuelVo** [comment]
Drag Ruler 1.3.4 should fix the compatibility issues.
