### ISSUE TITLE
Add translate french

### ISSUE THREAD

**Issue by Elfenduil** [manuelVo/foundryvtt-terrain-ruler#20]
Hi,

Can you add the translate french in you module, see file in Att

Thank you
[Traduire Terrain ruler.txt](https://github.com/manuelVo/foundryvtt-terrain-ruler/files/7595410/Traduire.Terrain.ruler.txt)

**Comment by CaosFR** [comment]
It's will be very great :)

**Comment by manuelVo** [comment]
This will be part of the v9 release

**Comment by manuelVo** [comment]
Thanks @Elfenduil
