### ISSUE TITLE
Terrain-ruler vs. libruler

### ISSUE THREAD

**Issue by ravingdragoon** [manuelVo/foundryvtt-terrain-ruler#21]
I am getting the following conflict in libWrapper. Is this an ignorable conflict, or will this cause problems with accurate measurements on difficult terrain?

```
terrain-ruler vs. libruler (x3)
- Ruler.prototype._highlightMeasurement (x1)
- Ruler.prototype.toJSON (x1)
- Ruler.prototype.update (x1)
```

**Comment by DawidIzydor** [comment]
afaik terrain ruler does not need libruler to work correcly, unless you're using it for other mods you are free to remove it

**Comment by ravingdragoon** [comment]
I us libruler for other modules

**Comment by apoapostolov** [comment]
Same, I use libruler with Drag Ruler (caewok version) and Pathfinding Ruler (caewok version)

**Comment by manuelVo** [comment]
I have no info on if this will work. Finding out whether it works is easy though: Measuring terrain will either fully work or fully fail. So if you can percieve any terrain measurements at all, they are very likely to be accurate

**Comment by manuelVo** [comment]
The important parts of libruler are now in core and with the v10 release of Terrain Ruler, these changes are integrated.
