### ISSUE TITLE
Support with foundry v9.X

### ISSUE THREAD

**Issue by CaosFR** [manuelVo/foundryvtt-terrain-ruler#23]
Hi,

Simple question that many would like to know. Is your module compatible with v9.X? Have any tests been carried out?

I'm refer to : https://docs.google.com/spreadsheets/d/1ppPR348igxL75M_G7dWl3otzXYpPwrnj7NVSDP8GmVw/edit#gid=0

Thanks
Bests regards

**Comment by manuelVo** [comment]
The v0.8 version works well in v9. A v9 uodate that officially supports v9 should be released in the next week weeks

**Comment by CaosFR** [comment]
Thanks for your quick reply.

**Comment by manuelVo** [comment]
Foundry v9 is fully supported since Terrain Ruler 1.5.1

**Comment by CaosFR** [comment]
Thanks for your work.
