### ISSUE TITLE
The option to run on/off Terrain Ruler doesn't work until page is refreshed

### ISSUE THREAD

**Issue by ckdragons** [manuelVo/foundryvtt-terrain-ruler#26]
This option is stuck until the page is refreshed.

**Comment by manuelVo** [comment]
Are you talking about the purple toggle or about the option in the settings menu? What needs to be done for the option to become stuck?

**Comment by ckdragons** [comment]
This would be the option in the settings menu.

**Comment by ckdragons** [comment]
The purple toggle is working normally.

**Comment by manuelVo** [comment]
In which way does the setting get stuck? When does this happen?

**Comment by ckdragons** [comment]
My apologies for not describing the issue clearly.  When I change the Terrain Ruler option in Settings, the change does not happen immediately when I click Save. Only when I refresh (F5) the web page does the change take effect. Doesn't matter whether the setting is switched to ON -> OFF or OFF -> ON.

Maybe it'll be better that this is removed since this can be controller from the purple button on the controls along the left screen. Unless of course, this Settings option has a larger purpose.

**Comment by ckdragons** [comment]
I agree, thank you for the explanation.  :)
