### ISSUE TITLE
Fails under Foundry v10

### ISSUE THREAD

**Issue by FoxLee** [manuelVo/foundryvtt-terrain-ruler#31]
Trying to use this module under v10 results in a bunch of "terrainRuler is not defined" errors (example attached).
Any chance a v10 update is forthcoming, or is that not likely for now?

![image](https://user-images.githubusercontent.com/10067730/189253879-ec8298b1-25b6-4051-b067-91a94a011d90.png)

**Comment by CaosFR** [comment]
You find a post for the update here : https://github.com/manuelVo/foundryvtt-terrain-ruler/issues/32

**Comment by manuelVo** [comment]
I've just released a v10 compatible version

**Comment by CaosFR** [comment]
thanks :)

**Comment by FoxLee** [comment]
Thank you! Your work is truly appreciated.
