### ISSUE TITLE
Any hope for a v10 support? 

### ISSUE THREAD

**Issue by nirurin** [manuelVo/foundryvtt-terrain-ruler#32]
Just thought I would ask the question, hoping to get a response or I may ask for the league to take over development as this module is required for the terrain module to actually function!

**Comment by manuelVo** [comment]
Yes, the module will be ported to v10. However I've got quite a long list of modules that broke with v10, so the port may take a while.

**Comment by CaosFR** [comment]
@manuelVo Thanks for your work, do you know a timeline for the update ?

**Comment by manuelVo** [comment]
If everything goes according to plan, the release should be out some time this week.

**Comment by manuelVo** [comment]
I've just released a v10 compatible version

**Comment by CaosFR** [comment]
Amazing thanks :)
