### ISSUE TITLE
Player using the ruler tool will freeze GM and other players' clients

### ISSUE THREAD

**Issue by pedrogrullada** [manuelVo/foundryvtt-terrain-ruler#33]
On Foundry V10 build 288, tested on both D&D 5e and PF2e systems.

Only 2 active modules are Enhanced Terrain Layer and Terrain Ruler. By having a player connected at the same time as the GM (and possibly other players), the player using the ruler will cause the GM's and other players' clients to crash (Oddly enough, the offending player's client continues to work). Due to the nature of the crashes I'm unable to provide any console information, and the bug will annoyingly refuse to happen sometimes, though I can still reproduce it semi-consistently.

**Comment by manuelVo** [comment]
Hi there. Thanks for the report! To have a chance to fix this bug I need more details about when this bug is happening. Is it possible for you to record a video that shows the interaction you're performing with Terrain Ruler to cause the freeze?

**Comment by pedrogrullada** [comment]
> Hi there. Thanks for the report! To have a chance to fix this bug I need more details about when this bug is happening. Is it possible for you to record a video that shows the interaction you're performing with Terrain Ruler to cause the freeze?

It's a little late for me but I will record a video tomorrow. I will try to get both perspectives.

In the meantime, using just words, the interaction is selecting the ruler tool and measuring, at which point the GM client freezes before the player ruler even appears on the screen, meanwhile the player is unhindered and the console is silent.

**Comment by manuelVo** [comment]
What kinds of terrain are placed on the scene?

**Comment by pedrogrullada** [comment]
No terrain at all, just a fresh scene

**Comment by manuelVo** [comment]
Thanks. I was able to reproduce this on my machine and will now start digging into the root cause of this

**Comment by manuelVo** [comment]
This bug is caused by an upstream bug: https://github.com/foundryvtt/foundryvtt/issues/8370

However, it should be possible to update Terrain Ruler for the time being to be able to deal with this bug if it occurs, so that Foundry won't freeze but instead only an invalid measurement is being displayed.

**Comment by manuelVo** [comment]
Terrain Ruler v1.7.2 contains a workaround for the upstream bug that should prevent the freezes from happening.

**Comment by dmarcuse** [comment]
This still seems to be happening intermittently. I poked around in devtools a bit after a freeze and it seems that [at this point in the code](https://github.com/manuelVo/foundryvtt-terrain-ruler/blob/develop/src/measure.js#L37) `ray.B` was an object, but the contained `x`/`y` values were `undefined` (or it may have been `NaN`, I should've taken a screenshot...).

**Comment by dmarcuse** [comment]
Update - I just managed to reproduce this freeze again - in this case, with `ray.B = { x: 9, y: NaN }`.

**Comment by manuelVo** [comment]
As mentioned, this is caused by a bug in Foundryvtt itself. It has been reported as https://github.com/foundryvtt/foundryvtt/issues/8370 , however they closed the issue, so it's unlikely this will ever get fixed

**Comment by dmarcuse** [comment]
In the meantime, could the workaround be updated? The freezes are frustrating and I'd like to continue to use this module. I'm happy to put together a PR if it would help.
