### ISSUE TITLE
Not respecting token/terrain elevation

### ISSUE THREAD

**Issue by dumptruckman** [manuelVo/foundryvtt-terrain-ruler#34]
This module (I think) doesn't seem to be accounting for the elevation of the terrain vs the elevation of the moving token. For example, a token at elevation 20 is still effected by difficult terrain that is set to elevation 40. This happens whether the token is above or below the terrain. If the token is above the terrain's elevation it should account for the depth of the terrain as well.

**Comment by manuelVo** [comment]
This is caused by a bug in Drag Ruler: https://github.com/manuelVo/foundryvtt-drag-ruler/issues/238
