### ISSUE TITLE
Terrain Ruler is doubling the distance measured

### ISSUE THREAD

**Issue by naesean** [manuelVo/foundryvtt-terrain-ruler#35]
I'm on a scene that has no terrain defined. If I have Terrain Ruler module enabled, then the measured distance is doubled. If I disable Terrain Ruler, then Drag Ruler calculates the distance correctly.

I tried disabling all modules except: Drag Ruler, Enhanced Terrain Layer, socketlib, and Terrain Ruler and the bug still occurs.

v10

**Comment by manuelVo** [comment]
Enhanced Terrain Layer just fixed a bug that could have been responsible for this. Please verify if this issue still persists with ETL 10.5

**Comment by naesean** [comment]
It's working now! Thanks
