### ISSUE TITLE
Not showing difficult terrain to players?

### ISSUE THREAD

**Issue by GaistH** [manuelVo/foundryvtt-terrain-ruler#42]
Apologies if this isn't specifically related to Terrain Ruler -- I'm not sure if this or Enhanced Terrain itself is supposed to handle this function.

PF1E for the system, in tandem with Drag Ruler: actors dragged by players don't reveal which spaces are difficult terrain to them, but show normally for a GM.

**Comment by manuelVo** [comment]
Check if the issue persists if you disable Terrain Ruler & Drag Ruler.

**Comment by GaistH** [comment]
It did, sorry for the bother!  Tangentially, is there any chance for PF1E to get support to identify terrain types an actor ignores difficult terrain on?  When I inquired with Monk, the direction was to check with the ruler creator.  Cheers!

**Comment by manuelVo** [comment]
That stuff is handled within the PF1 system itself, so any changes in that direction would need to be made there. Alternatively, this could be done by creating a new module dedicated for that functionality. I've been thinking about implementing this in PF1, but last time I checked there were prerequisites missing implementing it in a way that I would consider good. So yes, the chance is there, but the chance that I'm going to be the person that's going to do it is low right now.

**Comment by GaistH** [comment]
Ahh, I see -- totally understandable then, especially given that it's mostly an older system for goofballs like me to still want to play.  While I'd certainly love for UI-driven configs or even just dflag keywords correlating with ETL's terrain types, I did have one notion for a possibly more straightforward bridge that ought to cover anyone's use-case in the meantime: maybe just a hotkey to temporarily ignore difficult terrain while plotting dragged token movement?  That way it would cover any terrain immunities or skill / class feature use to circumvent obstacles or anything else that might be the case on the fly and would probably be a solid stopgap until such a time that messing with a fancier / prettier solution might be in the cards.

In any event, I appreciate the response -- and the rad work you've put in to making this play possible in the first place!

**Comment by manuelVo** [comment]
Adding a hotkey to ignore terrain is certainly a reasonable request that I could investigate.
