### ISSUE TITLE
New Error Message when using Terrain Ruler

### ISSUE THREAD

**Issue by Deadlander** [manuelVo/foundryvtt-terrain-ruler#45]
Been getting a new error message when using Terrain Ruler:
![image](https://user-images.githubusercontent.com/13036735/220248249-a4ecb56c-1299-4c59-93a0-64a2e325d156.png)

Not sure what the issue is, and it only seems to happen when playing PF2E.

**Comment by manuelVo** [comment]
This warning is emitted by the pf2 drag ruler integration
