### ISSUE TITLE
Terrain Ruler + Hex Token Size Support cause measure distance function not to work

### ISSUE THREAD

**Issue by dirusulixes** [manuelVo/foundryvtt-terrain-ruler#5]
with only Hex Token Size Support + Terrain Ruler and Terrain Layer, the ruler is not drawn when I select the Measure Distance button in the Basic Controls. Disactivating  either Terrain Ruler or Hex Token Size Support makes it work again. I don't see any relevant console output.

**Comment by manuelVo** [comment]
Related PR in Hex Token Size Support: https://github.com/Ourobor/Hex-Size-Support/pull/10
