### ISSUE TITLE
TerrrainRuler Disabling Measure Distance Button Function

### ISSUE THREAD

**Issue by BadGenerator** [manuelVo/foundryvtt-terrain-ruler#6]
When TerrainLayer is enabled, the default Measure Distance button does not show the measuring rule, but DragRuler still works.
The button Measure Distance With Difficult Terrain does not work. Enabling or Disabling it makes no diference on DragRuler. And, since the Measure Distance button is not working with TerrainLayer module enabled, i couldn't check if the Measure Distance With Difficult Terrain button works with the default system rule.

Found the problem... As the Changelog says, Terrain Ruler is imcompatible with Hex Token Size Support versions before 0.55. But there is no Hex Token Size Support 0.55 version released yet.

**Comment by manuelVo** [comment]
Hex Token Size Support 0.5.5 is now released.
