### ISSUE TITLE
"costGrid is deprecated, please use the cost function instead"

### ISSUE THREAD

**Issue by Doresain** [manuelVo/foundryvtt-terrain-ruler#8]
When using Terrain Ruler with Enhanced Terrain Layer, the console shows this warning repeatedly while dragging. Additionally, the Enhanced Terrain Layer feature to treat other tokens as difficult terrain does not function.
![image](https://user-images.githubusercontent.com/26096062/113939595-0becb580-97b1-11eb-8a09-55b4b478a29b.png)
In https://github.com/ironmonk88/enhanced-terrain-layer/issues/7, ironmonk88 says 

```
I believe Terrain Ruler is still using old functionality.
If there's a comment in the console log about costGrid being deprecated, then that would be the issue.
I think Terrain Ruler is going to release an update soon, but I'm not sure.
```
Filing this just to track that change. Thanks for the great module!

**Comment by manuelVo** [comment]
Thank you for the kind words and thanks for reporting this.

Terrain Ruler does fully support Enhanced Terrain Ruler. The module Drag Ruler is responsible for these messages and for the bugs you're experiencing. [This is the Drag Ruler issue that tracks Enhanced Terrain Layer support in Drag Ruler](https://github.com/manuelVo/foundryvtt-drag-ruler/issues/50).
