### ISSUE TITLE
Misleading Error Message

### ISSUE THREAD

**Issue by Sinaloit** [manuelVo/foundryvtt-terrain-ruler#9]
The error message in this code section refers to game.terrainLayer when it is actually game.terrainRuler that is causing the deprecation warning.
https://github.com/manuelVo/foundryvtt-terrain-ruler/blob/7f18f91674e5bb1f7cf0954b6bceef66909d178b/src/main.js#L17-L22

**Comment by manuelVo** [comment]
Whoops. To many Terrain*-modules to work with. Thanks for reporting this!
